(()=>{
  'use strict';
  const API='https://admin-proxy-v2-production.up.railway.app/api/noktena-admin';
  const $=s=>document.querySelector(s);
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const money=n=>`${Math.round(Number(n)||0).toLocaleString('ru-RU')} ₽`;
  function sess(){try{return JSON.parse(localStorage.getItem('nkt-adm2')||'null')}catch{return null}}
  async function api(action,options={}){const headers={...(options.headers||{})},s=sess();if(s?.access_token)headers.Authorization='Bearer '+s.access_token;const r=await fetch(API+'?action='+encodeURIComponent(action),{...options,headers});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||'Ошибка сервера');return d}
  function ensure(){if($('#ordersOpen'))return;const actions=document.querySelector('.main .top .actions');if(actions){const btn=document.createElement('button');btn.id='ordersOpen';btn.type='button';btn.className='btn secondary';btn.textContent='Заказы';const add=$('#add');actions.insertBefore(btn,add||null);btn.addEventListener('click',open)}const modal=document.createElement('div');modal.id='ordersModal';modal.className='modal hide';modal.innerHTML=`<div class="modalbox"><div class="modalhead"><div><b>Заказы с сайта</b><div class="muted">Новые заявки из корзины и оформления заказа.</div></div><div class="actions"><button id="ordersReload" class="btn secondary" type="button">Обновить</button><button id="ordersClose" class="btn secondary" type="button">Закрыть</button></div></div><div id="ordersList" style="display:grid;gap:12px;margin-top:14px"></div></div>`;document.body.appendChild(modal);$('#ordersClose').addEventListener('click',()=>modal.classList.add('hide'));$('#ordersReload').addEventListener('click',load)}
  const statusLabels={new:'Новый',confirmed:'Подтверждён',processing:'В работе',done:'Выполнен',cancelled:'Отменён'};
  function render(rows){const mount=$('#ordersList');if(!rows.length){mount.innerHTML='<div class="notice">Заказов пока нет.</div>';return}mount.innerHTML=rows.map(o=>{const items=Array.isArray(o.items)?o.items:[];return `<article style="border:1px solid var(--line);border-radius:16px;padding:15px;background:#fff"><div style="display:flex;justify-content:space-between;gap:14px;align-items:flex-start;flex-wrap:wrap"><div><b style="font-size:18px">Заказ № ${esc(o.order_no)}</b><div class="muted">${new Date(o.created_at).toLocaleString('ru-RU')}</div></div><select data-order-status="${esc(o.id)}" style="width:auto;min-width:170px"><option value="new" ${o.status==='new'?'selected':''}>Новый</option><option value="confirmed" ${o.status==='confirmed'?'selected':''}>Подтверждён</option><option value="processing" ${o.status==='processing'?'selected':''}>В работе</option><option value="done" ${o.status==='done'?'selected':''}>Выполнен</option><option value="cancelled" ${o.status==='cancelled'?'selected':''}>Отменён</option></select></div><div style="display:grid;grid-template-columns:repeat(auto-fit,minmax(210px,1fr));gap:8px;margin-top:12px"><div><b>${esc(o.customer_name)}</b><div>${esc(o.phone)}</div>${o.email?`<div>${esc(o.email)}</div>`:''}</div><div><b>Получение</b><div>${o.delivery_method==='pickup'?'Самовывоз':'Доставка'}</div>${o.address?`<div>${esc(o.city||'')} ${esc(o.address)}</div>`:''}<div>Подъём: ${o.lift_method==='cargo'?'грузовой лифт':o.lift_method==='stairs'?`лестница, этаж ${esc(o.floor)}`:'не нужен'}</div>${o.assembly_requested?'<div>Сборка кровати: да</div>':''}</div><div><b>Сумма</b><div>Товары: ${money(o.subtotal)}</div><div>Доставка: ${money(o.delivery_cost)}</div><div>Подъём: ${money(o.lift_cost)}</div><div>Сборка: ${money(o.assembly_cost)}</div><div style="font-size:17px;font-weight:900">Итого: ${money(o.total)}</div></div></div><div style="margin-top:12px;padding-top:10px;border-top:1px solid #edf2ef">${items.map(x=>`<div style="padding:5px 0"><b>${esc(x.name)}</b> × ${esc(x.qty)} — ${money((Number(x.price)||0)*(Number(x.qty)||1))}${x.size?` · ${esc(x.size)}`:''}${x.color?` · ${esc(x.color)}`:''}</div>`).join('')}</div>${o.comment?`<div class="notice" style="margin-top:10px">Комментарий: ${esc(o.comment)}</div>`:''}</article>`}).join('')}
  async function load(){const mount=$('#ordersList');mount.innerHTML='<div class="muted">Загрузка заказов…</div>';try{const d=await api('orders');render(d.orders||[])}catch(e){mount.innerHTML=`<div style="color:#b82e3b">${esc(e.message)}</div>`}}
  async function open(){ensure();$('#ordersModal').classList.remove('hide');await load()}
  document.addEventListener('change',async e=>{const s=e.target.closest('[data-order-status]');if(!s)return;try{await api('order-status',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({id:s.dataset.orderStatus,status:s.value})});if(typeof toast==='function')toast('Статус заказа обновлён')}catch(err){if(typeof toast==='function')toast(err.message,true)}});
  ensure();
})();