from pathlib import Path


def replace_once(text, old, new, label):
    if old not in text:
        raise SystemExit(f'{label}: target not found')
    if text.count(old) != 1:
        raise SystemExit(f'{label}: expected one target, found {text.count(old)}')
    return text.replace(old, new, 1)

p = Path('admin/admin.js')
s = p.read_text(encoding='utf-8')

old = '''        <div class="color-image-controls">\n          <select data-color-image-select="${esc(color)}">${options}</select>\n          ${selected ? `<button type="button" class="color-image-delete" data-color-image-remove="${esc(color)}">Удалить фото</button>` : ''}\n        </div>'''
new = '''        <div class="color-image-controls">\n          <select data-color-image-select="${esc(color)}">${options}</select>\n          <button type="button" class="color-image-upload-btn" data-color-image-upload-trigger="${esc(color)}">+ Загрузить фото</button>\n          <input type="file" accept="image/*,.jpg,.jpeg,.png,.webp,.gif,.avif,.heic,.heif" data-color-image-upload="${esc(color)}" hidden>\n          ${selected ? `<button type="button" class="color-image-delete" data-color-image-remove="${esc(color)}">Удалить фото</button>` : ''}\n        </div>'''
s = replace_once(s, old, new, 'color controls')

old = '''  async function uploadStorageObject(file, bucket, encodedPath, retried = false) {\n    const r = await fetch(`${baseUrl()}/storage/v1/object/${encodeURIComponent(bucket)}/${encodedPath}`, {\n      method:'POST',\n      headers:authHeaders({\n        'Content-Type':file.type || 'application/octet-stream',\n        'x-upsert':'false',\n        'cache-control':'3600'\n      }),\n      body:file\n    });'''
new = '''  async function uploadStorageObject(file, bucket, encodedPath, retried = false) {\n    const r = await fetch(`${baseUrl()}/storage/v1/object/${encodeURIComponent(bucket)}/${encodedPath}`, {\n      method:'POST',\n      headers:authHeaders({\n        'Content-Type':file.type || 'application/octet-stream',\n        'x-upsert':'false'\n      }),\n      body:file\n    });'''
s = replace_once(s, old, new, 'storage upload headers')

old = '''  async function uploadImages(files) {\n    if (!files?.length) return;\n    if (!state.session?.access_token) throw new Error('Сессия администратора не найдена. Войдите заново.');\n    const key = $('#editKey').value || `new-${Date.now()}`;\n    const bucket = cfg.storageBucket || 'product-images';\n    const validFiles = [...files].filter(file => String(file?.type || '').startsWith('image/'));\n    if (!validFiles.length) throw new Error('Выберите файл изображения: JPG, PNG, WEBP, GIF или AVIF.');\n    for (const file of validFiles) {\n      const ext = uploadExtension(file);\n      const random = (globalThis.crypto?.randomUUID?.() || Math.random().toString(36).slice(2)).replace(/[^a-z0-9-]/gi, '');\n      const name = `${Date.now()}-${random}.${ext}`;\n      const path = `products/${asciiProductFolder(key)}/${name}`;\n      const encoded = path.split('/').map(encodeURIComponent).join('/');\n      await uploadStorageObject(file, bucket, encoded);\n      state.editImages.push(`${baseUrl()}/storage/v1/object/public/${encodeURIComponent(bucket)}/${encoded}`);\n    }\n    renderImages();\n    renderColorImageBindings();\n    toast(validFiles.length === 1 ? 'Фотография загружена' : `Фотографии загружены: ${validFiles.length}`);\n  }'''
new = '''  function isImageFile(file) {\n    const type = String(file?.type || '').toLowerCase();\n    if (type.startsWith('image/')) return true;\n    return /\\.(jpe?g|png|webp|gif|avif|heic|heif)$/i.test(String(file?.name || ''));\n  }\n\n  function publicStorageUrl(bucket, encodedPath) {\n    return `${baseUrl()}/storage/v1/object/public/${encodeURIComponent(bucket)}/${encodedPath}`;\n  }\n\n  async function uploadSingleImage(file, folderSuffix = '') {\n    if (!state.session?.access_token) throw new Error('Сессия администратора не найдена. Войдите заново.');\n    if (!isImageFile(file)) throw new Error('Выберите файл изображения: JPG, PNG, WEBP, GIF, AVIF, HEIC или HEIF.');\n    const key = $('#editKey').value || `new-${Date.now()}`;\n    const bucket = cfg.storageBucket || 'product-images';\n    const ext = uploadExtension(file);\n    const random = (globalThis.crypto?.randomUUID?.() || Math.random().toString(36).slice(2)).replace(/[^a-z0-9-]/gi, '');\n    const name = `${Date.now()}-${random}.${ext}`;\n    const suffix = folderSuffix ? `/${folderSuffix}` : '';\n    const path = `products/${asciiProductFolder(key)}${suffix}/${name}`;\n    const encoded = path.split('/').map(encodeURIComponent).join('/');\n    await uploadStorageObject(file, bucket, encoded);\n    return publicStorageUrl(bucket, encoded);\n  }\n\n  async function uploadImages(files) {\n    if (!files?.length) return [];\n    const validFiles = [...files].filter(isImageFile);\n    if (!validFiles.length) throw new Error('Выберите файл изображения: JPG, PNG, WEBP, GIF, AVIF, HEIC или HEIF.');\n    const uploaded = [];\n    for (const file of validFiles) {\n      const url = await uploadSingleImage(file);\n      state.editImages.push(url);\n      uploaded.push(url);\n      renderImages();\n      renderColorImageBindings();\n    }\n    toast(validFiles.length === 1 ? 'Фотография загружена' : `Фотографии загружены: ${validFiles.length}`);\n    return uploaded;\n  }\n\n  async function uploadColorImage(color, file) {\n    color = String(color || '').trim();\n    if (!color) throw new Error('Не удалось определить цвет.');\n    const url = await uploadSingleImage(file, `colors/${asciiProductFolder(color)}`);\n    state.editColorImages[color] = url;\n    renderColorImageBindings();\n    toast(`Фото для цвета «${color}» загружено и привязано`);\n    return url;\n  }'''
s = replace_once(s, old, new, 'upload functions')

old = '''      const colorRm = e.target.closest('[data-color-image-remove]'); if (colorRm) {'''
new = '''      const colorUploadTrigger = e.target.closest('[data-color-image-upload-trigger]'); if (colorUploadTrigger) {\n        const color = String(colorUploadTrigger.dataset.colorImageUploadTrigger || '').trim();\n        const input = $$('[data-color-image-upload]').find(el => String(el.dataset.colorImageUpload || '').trim() === color);\n        if (input) input.click();\n      }\n      const colorRm = e.target.closest('[data-color-image-remove]'); if (colorRm) {'''
s = replace_once(s, old, new, 'color upload trigger')

old = '''    document.addEventListener('change', e => {\n      const select = e.target.closest('[data-color-image-select]');\n      if (!select) return;\n      const color = String(select.dataset.colorImageSelect || '').trim();\n      if (select.value) state.editColorImages[color] = select.value;\n      else delete state.editColorImages[color];\n      renderColorImageBindings();\n    });'''
new = '''    document.addEventListener('change', async e => {\n      const uploadInput = e.target.closest('[data-color-image-upload]');\n      if (uploadInput) {\n        const color = String(uploadInput.dataset.colorImageUpload || '').trim();\n        const file = uploadInput.files?.[0];\n        if (!file) return;\n        const trigger = $$('[data-color-image-upload-trigger]').find(el => String(el.dataset.colorImageUploadTrigger || '').trim() === color);\n        if (trigger) { trigger.disabled = true; trigger.textContent = 'Загружаем…'; }\n        try {\n          await uploadColorImage(color, file);\n        } catch (err) {\n          console.error(err);\n          toast(err.message || 'Не удалось загрузить фото для цвета', true);\n        } finally {\n          uploadInput.value = '';\n          renderColorImageBindings();\n        }\n        return;\n      }\n      const select = e.target.closest('[data-color-image-select]');\n      if (!select) return;\n      const color = String(select.dataset.colorImageSelect || '').trim();\n      if (select.value) state.editColorImages[color] = select.value;\n      else delete state.editColorImages[color];\n      renderColorImageBindings();\n    });'''
s = replace_once(s, old, new, 'delegated color upload change')

old = '''    $('#addImageUrl').addEventListener('click', () => { const u=$('#imageUrlInput').value.trim(); if(u){state.editImages.push(u);$('#imageUrlInput').value='';renderImages();renderColorImageBindings();} });\n    $('#imageUpload').addEventListener('change', async e => { const input=e.target; try { toast('Загружаем фотографию…'); await uploadImages([...input.files]); } catch(err){ console.error(err); toast(err.message || 'Не удалось загрузить фото',true); } finally { input.value=''; } });'''
new = '''    $('#addImageUrl').addEventListener('click', () => { const u=$('#imageUrlInput').value.trim(); if(u){state.editImages.push(u);$('#imageUrlInput').value='';renderImages();renderColorImageBindings();} });\n    $('#imageUploadButton')?.addEventListener('click', () => $('#imageUpload')?.click());\n    $('#imageUpload').addEventListener('change', async e => {\n      const input = e.target;\n      const button = $('#imageUploadButton');\n      const status = $('#imageUploadStatus');\n      const files = [...input.files];\n      if (!files.length) return;\n      if (button) { button.disabled = true; button.textContent = 'Загружаем…'; }\n      if (status) { status.className = 'upload-status'; status.textContent = `Загрузка: ${files.length} файл(а)…`; }\n      try {\n        await uploadImages(files);\n        if (status) { status.className = 'upload-status success'; status.textContent = 'Фото загружено. Не забудьте нажать «Сохранить» в карточке.'; }\n      } catch(err) {\n        console.error(err);\n        if (status) { status.className = 'upload-status error'; status.textContent = err.message || 'Не удалось загрузить фото'; }\n        toast(err.message || 'Не удалось загрузить фото',true);\n      } finally {\n        input.value='';\n        if (button) { button.disabled = false; button.textContent = '+ Загрузить фото'; }\n      }\n    });'''
s = replace_once(s, old, new, 'main upload binding')

p.write_text(s, encoding='utf-8')

p = Path('admin/index.html')
s = p.read_text(encoding='utf-8')
old = '''<div class="section-head"><div><h3>Фотографии</h3><p>Первая фотография используется как главная.</p></div><label class="upload-btn">+ Загрузить фото<input id="imageUpload" type="file" accept="image/*" multiple hidden></label></div>\n        <div id="imageGrid" class="image-grid"></div>'''
new = '''<div class="section-head"><div><h3>Фотографии</h3><p>Первая фотография используется как главная.</p></div><div><button id="imageUploadButton" type="button" class="upload-btn">+ Загрузить фото</button><input id="imageUpload" type="file" accept="image/*,.jpg,.jpeg,.png,.webp,.gif,.avif,.heic,.heif" multiple hidden></div></div>\n        <div id="imageUploadStatus" class="upload-status" aria-live="polite"></div>\n        <div id="imageGrid" class="image-grid"></div>'''
s = replace_once(s, old, new, 'main upload html')
s = s.replace('admin.css?v=20260919-colorphotos1', 'admin.css?v=20260919-photoupload3')
s = s.replace('admin.js?v=20260919-authfix1', 'admin.js?v=20260919-photoupload3')
p.write_text(s, encoding='utf-8')

p = Path('admin/admin.css')
s = p.read_text(encoding='utf-8')
s += '''\n.upload-status{min-height:18px;margin:-4px 0 9px;font-size:11px;color:var(--mut)}.upload-status.success{color:#16704a;font-weight:700}.upload-status.error{color:var(--danger);font-weight:700}.color-image-controls{flex-wrap:wrap}.color-image-upload-btn{border:1px solid #cfe0d7;background:#fff;color:#255745;border-radius:10px;padding:0 12px;height:42px;font:inherit;font-size:10px;font-weight:800;cursor:pointer;white-space:nowrap}.color-image-upload-btn:hover{background:#f3f8f5}.color-image-upload-btn:disabled{opacity:.6;cursor:wait}@media(max-width:760px){.color-image-upload-btn{width:100%}}\n'''
p.write_text(s, encoding='utf-8')
