const SUPABASE_URL=Deno.env.get('SUPABASE_URL')||'';
const SERVICE_KEY=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')||'';
const PUBLIC_KEY=Deno.env.get('SUPABASE_ANON_KEY')||'';
const RAW='https://raw.githubusercontent.com/rebrops-del/noktena/main/';
const BUCKET='product-images';
const CATEGORIES=new Set(['mattress','beds','sofas']);
function cors(){return {'access-control-allow-origin':'*','access-control-allow-methods':'GET,POST,OPTIONS','access-control-allow-headers':'authorization,content-type,apikey,x-client-info','access-control-max-age':'86400','cache-control':'no-store'}}
function J(x:unknown,s=200){return new Response(JSON.stringify(x),{status:s,headers:{...cors(),'content-type':'application/json; charset=utf-8'}})}
const svc=(x:Record<string,string>={})=>({apikey:SERVICE_KEY,Authorization:'Bearer '+SERVICE_KEY,...x});
async function authUser(token:string){if(!token)return null;const r=await fetch(SUPABASE_URL+'/auth/v1/user',{headers:{apikey:PUBLIC_KEY,Authorization:'Bearer '+token}});if(!r.ok)return null;return await r.json()}
async function verifyAdmin(req:Request){const a=req.headers.get('authorization')||'',t=a.startsWith('Bearer ')?a.slice(7):'',u=await authUser(t);if(!u?.id)throw new Error('AUTH_EXPIRED');const r=await fetch(SUPABASE_URL+'/rest/v1/admin_users?select=user_id&user_id=eq.'+encodeURIComponent(u.id),{headers:svc({Accept:'application/json'})});if(!r.ok)throw new Error('ADMIN_CHECK_FAILED');const rows=await r.json();if(!rows.length)throw new Error('FORBIDDEN');return u}
async function login(req:Request){const b=await req.json();const r=await fetch(SUPABASE_URL+'/auth/v1/token?grant_type=password',{method:'POST',headers:{apikey:PUBLIC_KEY,'content-type':'application/json'},body:JSON.stringify({email:String(b.email||''),password:String(b.password||'')})});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error_description||d.msg||'LOGIN_FAILED');const u=await authUser(d.access_token);if(!u?.id)throw new Error('LOGIN_FAILED');const ar=await fetch(SUPABASE_URL+'/rest/v1/admin_users?select=user_id&user_id=eq.'+encodeURIComponent(u.id),{headers:svc({Accept:'application/json'})});const admins=await ar.json();if(!ar.ok||!admins.length)throw new Error('FORBIDDEN');return d}
async function refresh(req:Request){const b=await req.json();const r=await fetch(SUPABASE_URL+'/auth/v1/token?grant_type=refresh_token',{method:'POST',headers:{apikey:PUBLIC_KEY,'content-type':'application/json'},body:JSON.stringify({refresh_token:String(b.refresh_token||'')})});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error_description||d.msg||'REFRESH_FAILED');return d}
async function changePassword(req:Request,user:any){
  const body=await req.json();
  const current=String(body.current_password||''),next=String(body.new_password||'');
  if(!current||next.length<12||next.length>128||current===next)throw new Error('INVALID_PASSWORD_INPUT');
  const loginResponse=await fetch(SUPABASE_URL+'/auth/v1/token?grant_type=password',{method:'POST',headers:{apikey:PUBLIC_KEY,'content-type':'application/json'},body:JSON.stringify({email:user.email,password:current})});
  if(!loginResponse.ok)throw new Error('INVALID_CURRENT_PASSWORD');
  const loginData=await loginResponse.json();
  const verified=await authUser(loginData.access_token);
  if(verified?.id!==user.id)throw new Error('INVALID_CURRENT_PASSWORD');
  const changed=await fetch(SUPABASE_URL+'/auth/v1/user',{method:'PUT',headers:{apikey:PUBLIC_KEY,Authorization:'Bearer '+loginData.access_token,'content-type':'application/json'},body:JSON.stringify({current_password:current,password:next})});
  if(!changed.ok)throw new Error('PASSWORD_UPDATE_FAILED');
}
async function fj(p:string){const r=await fetch(RAW+p,{headers:{accept:'application/json'},cache:'no-store'});if(!r.ok)throw new Error(p+' HTTP '+r.status);return await r.json()}
async function catalog(){const all=await Promise.all([fj('data/furniture.json'),fj('data/data1.json'),fj('data/data2.json'),fj('data/data3.json'),fj('data/data4.json'),fj('data/data5.json'),fj('data/data6.json')]);const f=all[0],base:any[]=[];for(const p of [...(f.beds||[]),...(f.sofas||[])])base.push({...p,_kind:'furniture',_key:'furniture:'+p.id,_isCustom:false,_changed:false,_hidden:false});for(const p of all.slice(1).flat())base.push({...p,_kind:'mattress',_key:'mattress:'+p.model,_isCustom:false,_changed:false,_hidden:false});const rr=await fetch(SUPABASE_URL+'/rest/v1/catalog_overrides?select=product_key,kind,payload,hidden,is_custom&order=updated_at.desc',{headers:svc({Accept:'application/json'})});if(!rr.ok)throw new Error('OVERRIDES_HTTP_'+rr.status);const rows=await rr.json(),m=new Map(rows.map((x:any)=>[x.product_key,x])),out:any[]=[];for(const x of base){const r:any=m.get(x._key);if(r?.hidden)continue;out.push(r?{...x,...r.payload,_changed:true,_hidden:false}:{...x})}for(const r of rows.filter((x:any)=>x.is_custom&&!x.hidden))out.push({...r.payload,_kind:r.kind,_key:r.product_key,_isCustom:true,_changed:true,_hidden:false});return out}
function clean(o:any){const x={...o};for(const k of Object.keys(x))if(k.startsWith('_'))delete x[k];return x}
async function save(body:any,user:any){const key=String(body.key||''),kind=String(body.kind||'');if(!key||!['furniture','mattress'].includes(kind))throw new Error('BAD_PRODUCT');const payload=clean(body.item||{}),source_id=kind==='furniture'?String(payload.id||'').replace(/^berhouse-/,''):String(payload.model||'');const row={product_key:key,kind,source_id,payload,hidden:!!body.hidden,is_custom:!!body.is_custom,updated_by:user.id};const r=await fetch(SUPABASE_URL+'/rest/v1/catalog_overrides?on_conflict=product_key',{method:'POST',headers:svc({'content-type':'application/json',Prefer:'resolution=merge-duplicates,return=minimal'}),body:JSON.stringify(row)});if(!r.ok)throw new Error((await r.text())||'SAVE_HTTP_'+r.status)}
async function upload(req:Request){const fd=await req.formData(),file=fd.get('file'),pk=String(fd.get('product_key')||'product');if(!(file instanceof File))throw new Error('FILE_REQUIRED');if(!file.type.startsWith('image/'))throw new Error('IMAGE_ONLY');if(file.size>12*1024*1024)throw new Error('FILE_TOO_LARGE');let h=2166136261;for(const c of pk){h^=c.charCodeAt(0);h=Math.imul(h,16777619)}const ext=(file.name.split('.').pop()||'jpg').toLowerCase().replace(/[^a-z0-9]/g,'').slice(0,5)||'jpg',path='products/p-'+(h>>>0).toString(36)+'/'+crypto.randomUUID()+'.'+ext,r=await fetch(SUPABASE_URL+'/storage/v1/object/'+BUCKET+'/'+path.split('/').map(encodeURIComponent).join('/'),{method:'POST',headers:svc({'content-type':file.type,'x-upsert':'false','cache-control':'31536000'}),body:new Uint8Array(await file.arrayBuffer())});if(!r.ok)throw new Error((await r.text())||'STORAGE_HTTP_'+r.status);return SUPABASE_URL+'/storage/v1/object/public/'+BUCKET+'/'+path.split('/').map(encodeURIComponent).join('/')}
async function getSettings(){const r=await fetch(SUPABASE_URL+'/rest/v1/category_settings?select=category,price_mode,price_value&order=category.asc',{headers:svc({Accept:'application/json'})});if(!r.ok)throw new Error('SETTINGS_HTTP_'+r.status);return await r.json()}
async function getDeliverySettings(){const r=await fetch(SUPABASE_URL+'/rest/v1/delivery_settings?select=delivery_price,lift_price,sofa_lift_surcharge,free_delivery_from&id=eq.true&limit=1',{headers:svc({Accept:'application/json'})});if(!r.ok)throw new Error('DELIVERY_SETTINGS_HTTP_'+r.status);const rows=await r.json();return rows[0]||{delivery_price:0,lift_price:0,sofa_lift_surcharge:0,free_delivery_from:0}}
function numberValue(v:any,name:string,min:number,max:number){const n=Number(v);if(!Number.isFinite(n)||n<min||n>max)throw new Error('BAD_'+name.toUpperCase());return n}
async function saveSettings(body:any){const rows=Array.isArray(body.rows)?body.rows:[];if(!rows.length)throw new Error('SETTINGS_REQUIRED');const cleanRows=rows.map((x:any)=>{const category=String(x.category||''),price_mode=String(x.price_mode||'percent');if(!CATEGORIES.has(category))throw new Error('BAD_CATEGORY');if(!['percent','fixed'].includes(price_mode))throw new Error('BAD_PRICE_MODE');const price_value=numberValue(x.price_value,'price_value',price_mode==='percent'?-90:-1000000,1000000);return{category,price_mode,price_value,updated_at:new Date().toISOString()}});const r=await fetch(SUPABASE_URL+'/rest/v1/category_settings?on_conflict=category',{method:'POST',headers:svc({'content-type':'application/json',Prefer:'resolution=merge-duplicates,return=minimal'}),body:JSON.stringify(cleanRows)});if(!r.ok)throw new Error((await r.text())||'SETTINGS_SAVE_HTTP_'+r.status);return cleanRows}
async function saveDeliverySettings(body:any,user:any){const row={id:true,delivery_price:numberValue(body.delivery_price,'delivery_price',0,1000000),lift_price:numberValue(body.lift_price,'lift_price',0,1000000),sofa_lift_surcharge:numberValue(body.sofa_lift_surcharge,'sofa_lift_surcharge',0,1000000),free_delivery_from:numberValue(body.free_delivery_from,'free_delivery_from',0,10000000),updated_at:new Date().toISOString(),updated_by:user.id};const r=await fetch(SUPABASE_URL+'/rest/v1/delivery_settings?on_conflict=id',{method:'POST',headers:svc({'content-type':'application/json',Prefer:'resolution=merge-duplicates,return=minimal'}),body:JSON.stringify(row)});if(!r.ok)throw new Error((await r.text())||'DELIVERY_SETTINGS_SAVE_HTTP_'+r.status);return row}
async function deliveryV2(){const r=await fetch(SUPABASE_URL+'/rest/v1/catalog_overrides?select=payload&product_key=eq.'+encodeURIComponent('settings:delivery_v2')+'&limit=1',{headers:svc({Accept:'application/json'})});if(!r.ok)return{};const rows=await r.json();return rows[0]?.payload||{}}
function text(v:any,max=500){return String(v??'').trim().slice(0,max)}
async function createOrder(req:Request){
  const b=await req.json();const name=text(b.customer_name,120),phone=text(b.phone,60);if(name.length<2)throw new Error('NAME_REQUIRED');if(phone.length<5)throw new Error('PHONE_REQUIRED');const rawItems=Array.isArray(b.items)?b.items:[];if(!rawItems.length||rawItems.length>50)throw new Error('ITEMS_REQUIRED');
  const items=rawItems.map((x:any)=>{const qty=Math.max(1,Math.min(20,Math.round(numberValue(x.qty||1,'qty',1,20))));const method=['none','cargo','stairs'].includes(String(x.lift_method))?String(x.lift_method):'none';const liftQty=method==='none'?0:Math.max(0,Math.min(qty,Math.round(Number(x.lift_qty)||0)));const liftFloor=method==='stairs'&&liftQty>0?Math.max(1,Math.min(50,Math.round(Number(x.lift_floor)||1))):0;return{kind:text(x.kind,20),category:text(x.category,20),key:text(x.key,180),name:text(x.name,220),size:text(x.size,100),color:text(x.color,120),price:numberValue(x.price,'item_price',0,10000000),qty,url:text(x.url,500),lift_method:liftQty>0?method:'none',lift_qty:liftQty,lift_floor:liftFloor,lift_cost:0}});
  const subtotal=items.reduce((s:number,x:any)=>s+x.price*x.qty,0),s=await deliveryV2();const deliveryMethod=['delivery','pickup'].includes(String(b.delivery_method))?String(b.delivery_method):'delivery';const deliveryPrice=Math.max(0,Number(s.delivery_price)||0),freeFrom=Math.max(0,Number(s.free_delivery_from)||0);const deliveryCost=deliveryMethod==='pickup'||(freeFrom>0&&subtotal>=freeFrom)?0:deliveryPrice;const cargo=Math.max(0,Number(s.cargo_lift_price)||0),stairs=Math.max(0,Number(s.stair_lift_price)||0),sofaSurcharge=Math.max(0,Number(s.sofa_lift_surcharge)||0),assemblyPrice=Math.max(0,Number(s.bed_assembly_price)||1500);
  let liftCost=0,liftCount=0;const methods=new Set<string>();let maxFloor=0;for(const x of items){if(deliveryMethod!=='delivery'){x.lift_method='none';x.lift_qty=0;x.lift_floor=0;x.lift_cost=0;continue}const q=Number(x.lift_qty)||0;if(q<=0||x.lift_method==='none')continue;let cost=0;if(x.lift_method==='cargo')cost=cargo*q;if(x.lift_method==='stairs'){cost=stairs*Math.max(1,Number(x.lift_floor)||1)*q;maxFloor=Math.max(maxFloor,Number(x.lift_floor)||0)}if(x.category==='sofas')cost+=sofaSurcharge*q;x.lift_cost=cost;liftCost+=cost;liftCount+=q;methods.add(x.lift_method)}
  const bedQty=items.filter((x:any)=>x.category==='beds').reduce((n:number,x:any)=>n+x.qty,0);const requestedAssembly=Math.max(0,Math.round(Number(b.assembly_qty)||0));const assemblyQty=!!b.assembly_requested&&bedQty>0?Math.min(bedQty,requestedAssembly||bedQty):0;const assemblyCost=assemblyQty*assemblyPrice;const total=subtotal+deliveryCost+liftCost+assemblyCost;const liftMethod=methods.size===0?'none':methods.size===1?[...methods][0]:'mixed';
  const row={status:'new',customer_name:name,phone,email:text(b.email,160)||null,city:text(b.city,120)||null,address:text(b.address,300)||null,comment:text(b.comment,1200)||null,delivery_method:deliveryMethod,lift_method:liftMethod,floor:maxFloor,assembly_requested:assemblyQty>0,assembly_qty:assemblyQty,lift_count:liftCount,items,subtotal,delivery_cost:deliveryCost,lift_cost:liftCost,assembly_cost:assemblyCost,total,source:'noktena.ru'};const r=await fetch(SUPABASE_URL+'/rest/v1/orders',{method:'POST',headers:svc({'content-type':'application/json',Prefer:'return=representation'}),body:JSON.stringify(row)});const data=await r.json().catch(()=>[]);if(!r.ok)throw new Error('ORDER_SAVE_FAILED');const order=data[0]||{};return{order_no:order.order_no,total:Number(order.total||total),created_at:order.created_at||new Date().toISOString(),lift_count:liftCount,assembly_qty:assemblyQty}}
async function listOrders(){const r=await fetch(SUPABASE_URL+'/rest/v1/orders?select=id,order_no,created_at,status,customer_name,phone,email,city,address,comment,delivery_method,lift_method,floor,lift_count,assembly_requested,assembly_qty,items,subtotal,delivery_cost,lift_cost,assembly_cost,total&order=created_at.desc&limit=200',{headers:svc({Accept:'application/json'})});if(!r.ok)throw new Error('ORDERS_HTTP_'+r.status);return await r.json()}
async function setOrderStatus(body:any){const id=text(body.id,80),status=text(body.status,30);if(!id||!['new','confirmed','processing','done','cancelled'].includes(status))throw new Error('BAD_ORDER_STATUS');const r=await fetch(SUPABASE_URL+'/rest/v1/orders?id=eq.'+encodeURIComponent(id),{method:'PATCH',headers:svc({'content-type':'application/json',Prefer:'return=minimal'}),body:JSON.stringify({status})});if(!r.ok)throw new Error('ORDER_STATUS_FAILED')}
Deno.serve(async req=>{if(req.method==='OPTIONS')return new Response(null,{status:204,headers:cors()});try{const u=new URL(req.url),a=u.searchParams.get('action')||'';if(a==='health')return J({ok:true,version:8});if(a==='login'&&req.method==='POST')return J({ok:true,session:await login(req)});if(a==='refresh'&&req.method==='POST')return J({ok:true,session:await refresh(req)});if(a==='create-order'&&req.method==='POST')return J({ok:true,order:await createOrder(req)},201);const user=await verifyAdmin(req);if(a==='change-password'&&req.method==='POST'){await changePassword(req,user);return J({ok:true})}if(a==='catalog'&&req.method==='GET')return J({ok:true,items:await catalog()});if(a==='settings'&&req.method==='GET')return J({ok:true,settings:await getSettings()});if(a==='settings-save'&&req.method==='POST')return J({ok:true,settings:await saveSettings(await req.json())});if(a==='delivery-settings'&&req.method==='GET')return J({ok:true,settings:await getDeliverySettings()});if(a==='delivery-settings-save'&&req.method==='POST')return J({ok:true,settings:await saveDeliverySettings(await req.json(),user)});if(a==='orders'&&req.method==='GET')return J({ok:true,orders:await listOrders()});if(a==='order-status'&&req.method==='POST'){await setOrderStatus(await req.json());return J({ok:true})}if(a==='save'&&req.method==='POST'){await save(await req.json(),user);return J({ok:true})}if(a==='save-many'&&req.method==='POST'){const b=await req.json(),rows=Array.isArray(b.rows)?b.rows:[];for(const x of rows)await save(x,user);return J({ok:true,count:rows.length})}if(a==='reset'&&req.method==='POST'){const b=await req.json(),r=await fetch(SUPABASE_URL+'/rest/v1/catalog_overrides?product_key=eq.'+encodeURIComponent(String(b.key||'')),{method:'DELETE',headers:svc({Prefer:'return=minimal'})});if(!r.ok)throw new Error(await r.text());return J({ok:true})}if(a==='upload'&&req.method==='POST')return J({ok:true,url:await upload(req)});return J({error:'NOT_FOUND'},404)}catch(e){const m=e instanceof Error?e.message:String(e),s=m==='AUTH_EXPIRED'?401:m==='FORBIDDEN'?403:['INVALID_PASSWORD_INPUT','INVALID_CURRENT_PASSWORD'].includes(m)?400:500;return J({ok:false,error:m},s)}});
